---
- name: copy file to remote host
  copy:
    src: files/{{item}}
    dest: /tmp
    mode: 1755
  with_items:
    - restore_template.sh
    - all-in-one-wp-migration.zip
    - all-in-one-wp-migration-url-extension.zip
  tags: restore

- name: run script in remote host
  shell: bash -x /tmp/restore_template.sh '{{ DOMAIN }}' '{{ source_restore_url }}'
  register: restore_log
  tags: restore

- debug: var=restore_log.stdout_lines
  tags: restore
